[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "frontend/dist"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
