[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "echo 'Functions only mode'"
  port = 8888
  framework = "#custom"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
